[package]
name = "rustls_example"
version = "0.1.0"
authors = ["PGP <pgp@gmx.it>"]
edition = "2018"

[dependencies]
rustls = "0.15.1"
hyper = "0.12.24"
hyper-rustls = "0.16.0"
tokio = "0.1.15"
futures = "0.1"
